# Generated by Django 4.0.1 on 2022-01-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='username'),
        ),
    ]
